### ISSUE TITLE
Add support for cloud storage

### ISSUE THREAD

**Issue by Crazyokd** [jaxvanyang/dotbackup#23]
Many cloud storage providers provide a certain amount of free capacity suitable for personal backup needs.

**Comment by jaxvanyang** [comment]
> Many cloud storage providers provide a certain amount of free capacity suitable for personal backup needs.

I want this tool to be as simple as possible, you can try to use hooks to upload backups to cloud.

Maybe something like:

```yaml
post_backup:
  - upload_to_cloud.sh "$BACKUP_DIR"
```
